name: Remote SSH
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PWD }}
        port: 22
        script: |
          cd wp-content/themes/writingor-wp-theme
          git pull
